[package]
name = "jtd-validate"
description = "Generates example data from JSON Typedef schemas"
version = "0.1.0"
license = "MIT"
authors = ["JSON Typedef Contributors"]
edition = "2018"

[dependencies]
jtd = "^0.2"
serde_json = "^1"
anyhow = "^1"
clap = "^2"
serde = "^1"
